name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: 262dfb0739da

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        date
        uname -a
        echo "${date} ---------------"
